name: My First Action

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Show date
        run: date

      - name: show files
        run: ls -la

      - name: print message
        run: echo "devops learning in progress"

